### ISSUE TITLE
Steps in composite actions now support "if:"

### ISSUE THREAD

**Issue by bewuethr** [chris48s/blogmarks#8]
Hi, I was just looking at https://chris48s.github.io/blogmarks/github/2021/11/06/composite-actions-reusable-workflows.html (and found it very helpful); one small remark: steps in composite actions now can use `if` conditions (see [docs](https://chris48s.github.io/blogmarks/github/2021/11/06/composite-actions-reusable-workflows.html)) &ndash; looks like this was [announced](https://github.blog/changelog/2021-11-09-github-actions-conditional-execution-of-steps-in-actions/) three days after you posted the article 😉

**Comment by chris48s** [comment]
Thanks :+1:  I've now added a note to the post about this.
